tests for tsweb-76
tech-stack-dev/ts-website-automation pull request #108
Opened 2023-04-02 21:20 UTC by YevheniiKel

2023-04-03 08:08 UTC, VladFedash requested changes

2023-04-03 08:08 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +		.fill('                                         '); // Many spaces
you can try to use smth like this
' '.repeat(n)

2023-04-03 08:08 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +
lb

2023-04-03 08:08 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/aboutUs/Careers_ContactUs.test.ts
> +		"                                         " // Many spaces
same

2023-04-03 09:53 UTC, YevheniiKel commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +
it's different test blocks separation

2023-04-03 10:21 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +
But it's the same test, at least I don't see one more test() construction in the current place.

2023-04-03 10:22 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	await driver.getByTestId(Career.Modal_lastNameInput).fill(" ".repeat(99));
Why did you choose the 99 magic number?)

2023-04-03 10:40 UTC, VladFedash approved these changes

2023-04-03 10:41 UTC, VladFedash approved these changes

2023-04-03 22:46 UTC, anastasiia-liashova requested changes

2023-04-03 22:46 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/aboutUs/Careers_ContactUs.test.ts
> +		const actualErrorText_FullName = await driver.getByTestId(ContactUs.fullNameInput).locator(Input.fieldErrorSelector).textContent();
`const actualErrorText_FullName = driver.getByTestId(ContactUs.fullNameInput).locator(Input.fieldErrorSelector);
await expect(actualErrorText_FullName ).toHaveText('Please enter your name');`

2023-04-03 22:46 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	await driver.locator(`[data-id*=${Containers.careerCardWithoutModifier}]`).nth(1).click();
await driver.getByTestId(/CardWrapper/).click();

2023-04-03 22:46 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	const actualErrorText_FirstName = await driver
`const actualErrorText_FirstName = driver.getByTestId(Career.Modal_firstNameInput).locator(Input.fieldErrorSelector);`

2023-04-03 22:46 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	expect(actualErrorText_FirstName).toEqual('Please enter your name');
`await expect(actualErrorText_FirstName).toHaveText('Please enter your name');`

2023-04-03 22:46 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	const actualErrorText_LastName = await driver
same

2023-04-03 22:46 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	expect(actualErrorText_LastName).toEqual('Please enter your last name');
same

2023-04-04 12:37 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/identifiers/Career.ts
> +	static ApplyNowButton = "ApplyNowButton-SharedApplyNow";
Use 'ApplyNow' button from Button class

2023-04-04 12:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/identifiers/Career.ts
> +	static Modal_lastNameInput = 'CareerInput-LastName';
same

2023-04-04 12:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/identifiers/Career.ts
> +	static Modal_sendRequestButton = 'SubmitButton-SharedSendMessage';
SendButton form Button class

2023-04-04 12:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/identifiers/ContactUs.ts
> +	static fullNameInput = 'ContactInput-FullName';
same

2023-04-04 12:41 UTC, anastasiia-liashova requested changes

2023-04-04 12:41 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	const actualErrorText_FirstName = await driver
without await

2023-04-04 16:06 UTC, anastasiia-liashova approved these changes

2023-04-04 18:41 UTC, anastasiia-liashova approved these changes

2023-04-05 10:45 UTC, DaniilVostrikov requested changes

2023-04-05 10:45 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlock.test.ts
> +import Input from '../../../identifiers/Input';
looks like it is not used in the current file

2023-04-05 10:46 UTC, DaniilVostrikov approved these changes

2023-04-05 12:19 UTC, merged