QA-TSWEB-560-Vlad
tech-stack-dev/ts-website-automation pull request #116
Opened 2023-04-06 19:52 UTC by VladFedash

2023-04-07 15:14 UTC, DaniilVostrikov requested changes

2023-04-07 15:14 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/steps/components/button/ButtonSteps.ts
> +
remove linebreak

2023-04-07 15:14 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/steps/components/container/ContainerSteps.ts
> +
same

2023-04-07 15:14 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/steps/components/job/DescriptionSteps.ts
> +
same

2023-04-10 15:23 UTC, DaniilVostrikov approved these changes

2023-04-10 15:23 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/steps/components/container/ContainerSteps.ts
> +
let's not separate verifications in the very small steps (about 3-4 line)

2023-04-10 15:23 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/steps/components/container/ContainerSteps.ts
> +
same

2023-04-10 15:23 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/steps/components/job/DescriptionSteps.ts
> +
same

2023-04-10 15:23 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockPart1.test.ts
> +
mb same?

2023-04-11 09:00 UTC, anastasiia-liashova approved these changes

2023-04-11 10:03 UTC, YevheniiKel approved these changes

2023-04-12 16:34 UTC, merged