new test for TSWEB-132
tech-stack-dev/ts-website-automation pull request #118
Opened 2023-04-09 22:13 UTC by YevheniiKel

2023-04-10 14:02 UTC, VladFedash requested changes

2023-04-10 14:02 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/navigationHeader/NavigationHeaderTests.test.ts
> +	await baseDriverSteps.checkUrl('https://tech-stack.com/blog/techstack-stands-with-ukraine/');
Add this URL to the UrlPath class and use UrlPath.YourURL instead

2023-04-10 14:03 UTC, VladFedash commented on ui_tests_playwright/automation/identifiers/Button.ts
> +	static LearnMoreButton = 'LearnMoreButton-SharedLearnMore2'
Does it a problem that the button data-id has a number at the end?

2023-04-10 14:13 UTC, anastasiia-liashova requested changes

2023-04-10 14:13 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/navigationHeader/NavigationHeaderTests.test.ts
> +	await expect(await driver.getByTestId(Button.LearnMoreButton)).toHaveText('Learn More');
without await 
await expect(driver.getByTestId....

2023-04-10 14:13 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/navigationHeader/NavigationHeaderTests.test.ts
> +	const buttonSwitcher = await (
same

2023-04-10 19:39 UTC, VladFedash approved these changes

2023-04-12 13:56 UTC, DaniilVostrikov requested changes

2023-04-12 13:56 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/navigationHeader/NavigationHeaderTests.test.ts
> +	// Uncomment when the data-id is added for the title element
Recommend to wait while jira-api logic will be pushed, and then push the test but with the appropriate ticket

2023-04-20 09:45 UTC, anastasiia-liashova requested changes

2023-04-20 09:45 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/navigationHeader/NavigationHeaderTests.test.ts
> +		{timeout: 1000}
try without "timeout"

2023-04-20 09:45 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/navigationHeader/NavigationHeaderTests.test.ts
> +	await expect((await driver.getByTestId(Blog.Blog_StandWithUkraineTitile))).toContainText(
without second await

2023-04-20 09:55 UTC, VladFedash requested changes

2023-04-20 09:55 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/navigationHeader/NavigationHeaderTests.test.ts
> +test('Check the the "Stand with Ukraine" block with localization @Regression @StandWithUkraine @TSWEB-132', async () => {
Check that*

2023-04-20 09:55 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/navigationHeader/NavigationHeaderTests.test.ts
> +	await buttonSwitcher.click();
What is the reason for creating the buttonSwitcher variable? You don't use this const anywhere more.

2023-04-21 12:30 UTC, anastasiia-liashova approved these changes

2023-04-22 08:37 UTC, VladFedash approved these changes

2023-04-22 08:52 UTC, merged