QA-TSWEB-560_Vlad
tech-stack-dev/ts-website-automation pull request #126
Opened 2023-04-14 21:59 UTC by VladFedash

2023-04-18 15:08 UTC, YevheniiKel requested changes

2023-04-18 15:08 UTC, YevheniiKel commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	expect(actualInputBoxProps?.width).toEqual(expectedInputBoxProps?.width);
why await was removed here?

2023-04-18 15:08 UTC, YevheniiKel commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +	await contentfulSteps.createCareerWithDefaultValue(
Maybe such pre-conditions need to be in the BeforeEach()?

2023-04-18 15:21 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	expect(actualInputBoxProps?.width).toEqual(expectedInputBoxProps?.width);
They aren't needed for these code lines. VS askes me this

2023-04-18 15:49 UTC, DaniilVostrikov requested changes

2023-04-18 15:49 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/enum/ColorEnum.ts
> +export enum ColorEnum {
ColorEnum => ColorsEnum

2023-04-18 15:49 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/utils/ContentfulUtils.ts
> +	async AddDefaultTags(directionsTag: DirectionsEnum, seniorityLevelsTag: SeniorityLevelsEnum) {
remove async and make it private

2023-04-18 15:49 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/utils/ContentfulUtils.ts
> +	async AddTagsToCareerBody(tagList: any[]) {
remove async and make it private

2023-04-18 17:45 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +	await contentfulSteps.createCareerWithDefaultValue(
done

2023-04-18 17:52 UTC, VladFedash commented on ui_tests_playwright/automation/utils/ContentfulUtils.ts
> +	async AddTagsToCareerBody(tagList: any[]) {
It couldn't be private, because we need to call this method outside of ContentfulUtils

2023-04-18 18:04 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +	const activeTagsGroupContainer = await containerSteps.getContainer(
I don't mind, but as for me, it's harder to read code.

2023-04-19 10:01 UTC, DaniilVostrikov approved these changes

2023-04-19 10:13 UTC, YevheniiKel approved these changes

2023-04-19 10:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/identifiers/Input.ts
> +	static FieldErrorSelector = "xpath=/following-sibling::div[@id='error']";
without "xpath="

2023-04-19 10:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	(await driver.component(ContainerByClass, Containers.SearchResultsTextContainer)).click();
maybe await at the beginning of the line

2023-04-19 10:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockPart1.test.ts
> +	await expect((await driver.component(ContainerByClass, Career.JobHeaderTitle)).Element).toHaveText(
Can you try without .Element?
`ContainerByClass, Career.JobHeaderTitle))).toHaveText(`

2023-04-19 10:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockPart2.test.ts
>  	const logoFooter = footerContainer.Element.getByTestId(Link.Logo);
same
try without .Element

2023-04-19 10:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +		careerMainContainer.Element
same
try without .Element

2023-04-19 10:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +		careerMainContainer.Element
same

2023-04-19 10:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +		careerMainContainer.Element
same

2023-04-19 10:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +		careerMainContainer.Element
same

2023-04-19 10:38 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +		const filterTag = filterGroupContainer.Element.getByTestId(tag);
same

2023-04-19 10:42 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockNoContentful.test.ts
> +	(await driver.component(ContainerByClass, Containers.SearchResultsTextContainer)).click();
added

2023-04-19 10:45 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockPart1.test.ts
> +	await expect((await driver.component(ContainerByClass, Career.JobHeaderTitle)).Element).toHaveText(
It doesn't work without

2023-04-19 10:46 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockPart2.test.ts
>  	const logoFooter = footerContainer.Element.getByTestId(Link.Logo);
it works

2023-04-19 10:54 UTC, VladFedash commented on ui_tests_playwright/automation/identifiers/Input.ts
> +	static FieldErrorSelector = "xpath=/following-sibling::div[@id='error']";
it doesn't work without

2023-04-19 10:56 UTC, merged

2023-04-19 10:56 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +		const activeTag = activeTagsGroupContainer.Element.getByTestId(tag);
same

2023-04-19 10:56 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/JobsBlock/JobsBlockPart2.test.ts
>  	const logoHeader = jobPageHeaderContainer.Element.getByTestId(Link.Logo);
same

2023-04-19 10:56 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SeniorityLevel.test.ts
> +	await activeTagsGroupContainer.Element.getByTestId(Button.ResetButton).click();
same

2023-04-19 10:56 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/navigationHeader/NavigationHeaderTests.test.ts
>  	const uaButtonSwitcher = headerContainer.Element.getByTestId(Button.UaLanguageSwitcher);
same