added SessionRandomValue class
tech-stack-dev/ts-website-automation pull request #13
Opened 2023-01-23 17:00 UTC by anastasiia-liashova

2023-01-30 18:46 UTC, DaniilVostrikov requested changes

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Components/Breadcrumbs.cs
> +}
if not taking too much time, please, replace this file with file from master to avoid this line ending changes:(

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Components/Tag.cs
> +}
same

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Components/Text.cs
> +    public class Text : BaseWebComponent
if i got it correct, this component not representing some text, it used in your code for getting some search results, for mee it looks like some different logic than 'Text' naming sounds

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Extensions/StringExtensions.cs
> +            if (string.IsNullOrEmpty(str))
why if the string is nullOrEmpty returns the exact string? Do we use this only for the cases where the source string has an "SRND" text? If yes and it uses for some structure maybe better to make it part of this structure? (for ex: As a property for the field from DTO)

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Models/Contentful/Career.cs
> +        public void FillWithDefaultData(SessionRandomValue sessionRandom, int number = 1)
Why did you decide to make it void type?

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Models/Contentful/Career.cs
> +            this.NameUs = this.NameUs.IsNullOrEmpty() ? $"Test{number}Career{randomValue}" : this.NameUs.AddRandom(sessionRandom);
please, contact me about these lines

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Models/Contentful/CareerDescription.cs
> +            this.AboutTheProjectUs = this.AboutTheProjectUs.IsNullOrEmpty() ? $"AboutTheProjectUs_{number}_{randomValue}" : this.AboutTheProjectUs.AddRandom(sessionRandom);
contact me about this one too

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Pages/ContactUsPage.cs
> +}
same as for the first file from the PR

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Pages/Job/JobPage.cs
> +}
same

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/RuntimeVariables/SessionRandomValue.cs
> +namespace CorelAutotestsCore.DTO.RunTimeVariables
![rock2](https://user-images.githubusercontent.com/82651667/215566892-22e548e7-32bb-41a7-ba4a-3efd813669c7.gif)

2023-01-30 18:46 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Utils/BrowserFactoryUtils/BrowserFactory.cs
>          {
please check the gitHub warnings above

2023-01-30 23:09 UTC, anastasiia-liashova commented on ui_tests/PlaywrightAutomation/Components/Text.cs
> +    public class Text : BaseWebComponent
it's like a text block component

2023-01-31 19:02 UTC, DaniilVostrikov requested changes

2023-01-31 19:02 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Steps/PageSteps/JobPageSteps.cs
> +            var expectedListTags = table.Rows.SelectMany(x => x.Values).ToList().Select(x=>x.AddRandom(_sessionRandom));
formating please

2023-02-06 10:50 UTC, VitaliiDolotov requested changes

2023-02-06 10:50 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/GeneralSteps.cs
> +
lb

2023-02-06 10:50 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/GeneralSteps.cs
> +            foreach (var tag in _createdTags.Value)
In order to decrease method complexity I would recommend to move those two cycles to separate methods

2023-02-07 19:26 UTC, DaniilVostrikov approved these changes

2023-02-07 19:39 UTC, VitaliiDolotov approved these changes

2023-02-07 19:39 UTC, merged