Move tests from .net solution to TS
tech-stack-dev/ts-website-automation pull request #136
Opened 2023-04-28 13:36 UTC by VladFedash

2023-05-03 10:48 UTC, YevheniiKel requested changes

2023-05-03 10:53 UTC, YevheniiKel requested changes

2023-05-03 10:53 UTC, YevheniiKel commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SearchField.test.ts
> +	const careerList = (await containerSteps.getContainer(ContainerByClass, Career.CareerList)).Element;
maybe it would be nice to ask UI devs to add the data-id?

2023-05-03 10:53 UTC, YevheniiKel commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/general/ResetVacancies.test.ts
> +		const careerMainContainer = await containerSteps.getContainer(ContainerByClass, Career.CareerMainBody);
same as above (data-id)
here and below

2023-05-04 11:13 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/SearchField.test.ts
> +	const careerList = (await containerSteps.getContainer(ContainerByClass, Career.CareerList)).Element;
Maybe, but I think, it's not necessary now and we can continue to use for these tests - classid

2023-05-04 11:13 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/careerBlock/sidebar/general/ResetVacancies.test.ts
> +		const careerMainContainer = await containerSteps.getContainer(ContainerByClass, Career.CareerMainBody);
Maybe, but I think, it's not necessary now and we can continue to use for these tests - classid

2023-05-04 11:21 UTC, anastasiia-liashova approved these changes

2023-05-04 12:22 UTC, YevheniiKel approved these changes

2023-05-05 11:06 UTC, DaniilVostrikov approved these changes

2023-05-10 13:06 UTC, merged