TSWEB-670 Add tests for UXUI design
tech-stack-dev/ts-website-automation pull request #139
Opened 2023-05-05 13:26 UTC by AnnaSlisenko

2023-05-05 17:04 UTC, VladFedash requested changes

2023-05-05 17:04 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/services/UxUiDesign.test.ts
> +test("Check Faq container from the 'UX/UI Design' block @Regression @UxUiDesign @TSWEB-670", async () => {
What do you certainly check in this test? What's mean 'Check Faq container'? Try to give more concrete info about certain test-case and what it checks.

2023-05-10 11:49 UTC, AnnaSlisenko commented on ui_tests_playwright/automation/identifiers/UxUiDesign.ts
> +	//Button
I`ll fix it

2023-05-10 11:52 UTC, AnnaSlisenko commented on ui_tests_playwright/automation/test/ui/services/UxUiDesign.test.ts
> +test("Check GetCustomUxAndUiDesignServices container from the 'UX/UI Design' block @Regression @UxUiDesign @TSWEB-670", async () => {
Ok, I`ll change namings

2023-05-10 12:02 UTC, AnnaSlisenko commented on ui_tests_playwright/automation/test/ui/services/UxUiDesign.test.ts
> +		[UxUiDesign.Instagram, 'https://www.instagram.com/techstack.design/'],
I suppose it is not necessary. These links are used only in current container

2023-05-10 14:21 UTC, VladFedash requested changes

2023-05-11 12:42 UTC, AnnaSlisenko commented on ui_tests_playwright/automation/test/ui/services/UxUiDesign.test.ts
> +test("Check RelatedServices container from the 'UX/UI Design' block @Regression @UxUiDesign @TSWEB-670", async () => {
This line is needed to continue the "for"  loop which checks correct redirections via arrows
It means like an "after" step, not "when" meaning)

2023-05-11 12:59 UTC, AnnaSlisenko commented on ui_tests_playwright/automation/test/ui/services/UxUiDesign.test.ts
> +		const [newPage] = await Promise.all([
Fixed

2023-05-11 12:59 UTC, AnnaSlisenko commented on ui_tests_playwright/automation/test/ui/services/UxUiDesign.test.ts
> +test("Check redirects in RelatedServices container from the 'UX/UI Design' block @Regression @UxUiDesign @TSWEB-670", async () => {
Fixed

2023-05-11 13:00 UTC, AnnaSlisenko commented on ui_tests_playwright/automation/test/ui/services/UxUiDesign.test.ts
> +test("Check Faq container from the 'UX/UI Design' block @Regression @UxUiDesign @TSWEB-670", async () => {
Fixed

2023-05-12 08:42 UTC, anastasiia-liashova approved these changes

2023-05-12 10:24 UTC, VladFedash approved these changes

2023-05-12 10:24 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/services/UxUiDesign.test.ts
I anyway think it's actual comment

2023-05-15 12:30 UTC, DaniilVostrikov requested changes

2023-05-16 15:10 UTC, anastasiia-liashova approved these changes

2023-05-16 15:10 UTC, DaniilVostrikov approved these changes

2023-05-19 15:22 UTC, merged