TSWEB-697 add tests for ConsaltingServ
tech-stack-dev/ts-website-automation pull request #149
Opened 2023-06-14 08:44 UTC by AnnaSlisenko

2023-06-14 09:20 UTC, VladFedash requested changes

2023-06-14 09:20 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/services/ConsultingService.test.ts
> +test("Check section titles  in 'Development process audit' container from the 'Consulting service' block @Regression @ConsultingService @TSWEB-697", async () => {
double spaces in test naming: 
...titles  in...

2023-06-14 09:20 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/services/ConsultingService.test.ts
> +test("Check section titles  in 'Software audit' container from the 'Consulting service' block @Regression @ConsultingService @TSWEB-697", async () => {
s

2023-06-14 09:20 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/services/ConsultingService.test.ts
> +	const clickCount = allSectionTitles.length - 1;
I don't see the reason to create this variable.

2023-06-15 13:18 UTC, closed without merging

2023-06-15 13:19 UTC, AnnaSlisenko commented
Obsolete