TSWEB-692 tests for Cloud & DevOps page
tech-stack-dev/ts-website-automation pull request #158
Opened 2023-07-12 08:42 UTC by Valerii-Kryvokhyzha

2023-07-12 09:43 UTC, AnnaSlisenko requested changes

2023-07-12 12:44 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/testData/ClutchReviewLinks.ts
> +export default class ClutchReviewLinks {
Thanks, I rewrite these classes and moved them to preconditionsData folder

2023-07-14 12:10 UTC, AnnaSlisenko approved these changes

2023-07-14 16:43 UTC, anastasiia-liashova approved these changes

2023-07-14 16:43 UTC, merged