TSWEB-694 add tests for AiMl
tech-stack-dev/ts-website-automation pull request #159
Opened 2023-07-12 10:06 UTC by AnnaSlisenko

2023-07-12 14:43 UTC, Valerii-Kryvokhyzha requested changes

2023-07-12 15:15 UTC, AnnaSlisenko commented on ui_tests_playwright/automation/identifiers/AiMlService.ts
> +	static AiBeneficialImpactOnIndustries = 'Container-AiImpact';
I'll fix it

2023-07-12 15:15 UTC, AnnaSlisenko commented on ui_tests_playwright/automation/test/ui/MainSite/services/AiMlService/AiMlServiceContent.test.ts
> +});
Yeah! Thanks! I will add such test

2023-08-01 08:42 UTC, anastasiia-liashova approved these changes

2023-08-01 11:46 UTC, Valerii-Kryvokhyzha approved these changes

2023-08-02 10:01 UTC, DaniilVostrikov approved these changes

2023-08-02 11:23 UTC, merged