TSWEB-955 Added tests for Healthcare page
tech-stack-dev/ts-website-automation pull request #169
Opened 2023-08-08 14:27 UTC by Valerii-Kryvokhyzha

2023-08-09 09:23 UTC, DaniilVostrikov approved these changes

2023-08-09 10:42 UTC, anastasiia-liashova approved these changes

2023-08-09 10:57 UTC, VladFedash requested changes

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/base/step/BaseDriverSteps.ts
> +		const clickAmount = clicksCount ? clicksCount : allSectionTitles.length - 1;
I don't see a reason to create additional variable, you can use clicksCount instead and overwrite it if it needed
clicksCount = clicksCount ? clicksCount : allSectionTitles.length - 1

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/preconditionsData/Links.ts
> +	static nuget = 'https://www.nuget.org/profiles/VitaliiDolotov';
Why is it different from other items?

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/CareerSite/aboutUs/AboutUsBlock.test.ts
> +	await engineeringCultureNextButton.click({clickCount: 3});
What does the number '3' mean?
Why did we choose this value?

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/MainSite/industries/Healthcare/HealthcareActions.test.ts
> +test("Check redirect by 'Read the full Case Study button' in 'Beats Screening Module by Techstack' container from the 'Healthcare' block @Regression @Healthcare @TSWEB-955", async () => {
I think the button shouldn't be inside '' quotes, isn't it?

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/MainSite/industries/Healthcare/HealthcareActions.test.ts
> +test("Check redirect by Clutch button in 'Beats Screening Module by Techstack' container from the 'Healthcare' block @Regression @Healthcare @TSWEB-955", async () => {
Why did you add quotes below for the button name, but skipped here?

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/MainSite/industries/Healthcare/HealthcareActions.test.ts
> +test("Check redirect by Breadcrumbs in header from the 'Healthcare' block @Regression @Healthcare @TSWEB-955", async () => {
same as below 
What is the object Breadcrumbs? Is it link or button or smth other?

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/MainSite/industries/Healthcare/HealthcareActions.test.ts
> +test("Check carousel sections, arrows and CTA button in 'How We Operate' container from the 'Healthcare' block @Regression @Healthcare @TSWEB-955", async () => {
same for button name

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/MainSite/industries/Healthcare/HealthcareActions.test.ts
> +	for (const entries of linkMap.entries()) {
Should 'entries' be const or let? 
I saw in other files a similar foreach with let. Choose o ne right option

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/MainSite/industries/Healthcare/HealthcareActions.test.ts
> +
remove lb

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/MainSite/industries/Healthcare/HealthcareActions.test.ts
> +	for (const [arrow, url] of arrowUrlMap) {
s

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/MainSite/industries/Healthcare/HealthcareContent.test.ts
> +test("Check section titles, image and CTA button in 'Beats Screening Module by Techstack' container from the 'Healthcare' block @Regression @Healthcare @TSWEB-955", async () => {
s

2023-08-09 10:57 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/generalComponents/generalContactUs/ContactUs.test.ts
> +	for (const url of Object.values(industryUrl)) {
s

2023-08-09 11:41 UTC, UncleDanya approved these changes

2023-08-09 16:36 UTC, VladFedash approved these changes

2023-08-10 09:30 UTC, DaniilVostrikov approved these changes

2023-08-10 10:33 UTC, merged