TSWEB-957 tests for renewable energy page
tech-stack-dev/ts-website-automation pull request #175
Opened 2023-08-21 07:41 UTC by Valerii-Kryvokhyzha

2023-08-21 09:22 UTC, anastasiia-liashova requested changes

2023-08-21 09:22 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/MainSite/industries/RenewableEnergy/RenewableEnergyActions.test.ts
> +	await newPage.waitForLoadState('networkidle');
where is the check?

2023-08-21 09:22 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/MainSite/industries/RenewableEnergy/RenewableEnergyActions.test.ts
> +	expect(await carousel.getByTestId(Container.SectionNumber).allInnerTexts()).toEqual([
Can you check `await expect(carousel.getByTestId(.......`

2023-08-21 09:22 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/MainSite/industries/RenewableEnergy/RenewableEnergyContent.test.ts
> +	expect(allBlockTitles.sort()).toEqual(testData.sort());
why did you use sort()?

2023-08-21 09:22 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/MainSite/industries/RenewableEnergy/RenewableEnergyContent.test.ts
> +	expect(await whoWeServeContainer.getByTestId(Container.SectionNumber).allInnerTexts()).toEqual([
same

2023-08-21 09:22 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/MainSite/industries/RenewableEnergy/RenewableEnergyContent.test.ts
> +	expect(allBlockTitles.sort()).toEqual(testDataBlockTitles.sort());
same

2023-08-21 09:22 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/MainSite/industries/RenewableEnergy/RenewableEnergyContent.test.ts
> +	expect(allSectionTitles.sort()).toEqual(testData.sort());
same

2023-08-21 09:22 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/MainSite/industries/RenewableEnergy/RenewableEnergyContent.test.ts
> +	expect(blockTitle).toEqual('Solar energy data portal scheme');
await expect ().haveText()

2023-08-28 14:03 UTC, anastasiia-liashova approved these changes

2023-08-28 14:05 UTC, DaniilVostrikov approved these changes

2023-08-28 14:07 UTC, merged