Tests for how we work page
tech-stack-dev/ts-website-automation pull request #178
Opened 2023-08-22 15:03 UTC by edward-astapov

2023-08-25 13:16 UTC, VladFedash approved these changes

2023-08-25 17:17 UTC, Valerii-Kryvokhyzha requested changes

2023-08-25 17:17 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/Buttons.ts
> +
Could you pls move these buttons to MainSiteButtons class?

2023-08-28 07:59 UTC, Valerii-Kryvokhyzha approved these changes

2023-09-01 08:59 UTC, merged