Tests for 'Custom Software development' page
tech-stack-dev/ts-website-automation pull request #179
Opened 2023-08-23 10:53 UTC by Viktoriia-Rublova

![image](https://github.com/tech-stack-dev/ts-website-automation/assets/82044379/dcb1c598-1ea3-47d6-a174-135c76223c49)

2023-08-23 13:43 UTC, Valerii-Kryvokhyzha requested changes

2023-08-23 13:43 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/CustomDev/CustomDevActions.test.ts
> +	for (let i = 0; i < numOfButtons; i++) {
Our dev team will fix Clutch links during this week

2023-08-25 17:30 UTC, Valerii-Kryvokhyzha approved these changes

2023-08-28 12:19 UTC, DaniilVostrikov approved these changes

2023-08-29 08:44 UTC, merged