Qa tsweb 1006
tech-stack-dev/ts-website-automation pull request #184
Opened 2023-08-28 14:22 UTC by KotliarovaK

2023-08-29 07:16 UTC, Valerii-Kryvokhyzha requested changes

2023-08-29 07:16 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/HomePage.test.ts
> +test("Check 'See All News' button from the 'Company insights' block on the 'Home' page @Regression @QaAsAService @TSWEB-603", async () => {
... from the 'Home' page @Regression @HomePage @TSWEB-1006

2023-08-29 07:16 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/MainSite/pages/HomePage.ts
> +    static CaseStudies = 'Container-CaseStudies';
Problem with the format, or its only on remote?

2023-08-29 07:16 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/HomePage.test.ts
> +	]);
Code format

2023-08-29 07:16 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/HomePage.test.ts
> +
mb better also add a check that this tab is active?

2023-08-29 08:28 UTC, KotliarovaK commented on ui_tests_playwright/automation/identifiers/MainSite/pages/HomePage.ts
> +    static CaseStudies = 'Container-CaseStudies';
Yes, it's only on the remote. I'll try to fix it.

2023-08-29 08:29 UTC, KotliarovaK commented on ui_tests_playwright/automation/test/ui/MainSite/HomePage.test.ts
> +	]);
I'll try to fix it.

2023-08-29 08:31 UTC, KotliarovaK commented on ui_tests_playwright/automation/test/ui/MainSite/HomePage.test.ts
> +
Thank you! I'll add it

2023-08-29 14:14 UTC, Valerii-Kryvokhyzha approved these changes

2023-08-30 11:49 UTC, DaniilVostrikov approved these changes

2023-09-04 14:22 UTC, closed without merging

2023-09-04 14:24 UTC, KotliarovaK commented
moved all the changes to the other one because of a branch error.