TSWEB-302-DanCodeFixes
tech-stack-dev/ts-website-automation pull request #19
Opened 2023-01-30 17:56 UTC by DaniilVostrikov

2023-01-30 23:42 UTC, anastasiia-liashova commented on ui_tests/PlaywrightAutomation/Pages/OurServices/QaAsServicePage.cs
> +    public string Container => "//div[@id='header']//parent::body";
are you sure this is correct?

2023-01-31 08:39 UTC, VitaliiDolotov requested changes

2023-01-31 08:39 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Pages/OurServices/QaAsServicePage.cs
> +        return Page.Locator($"//h3[contains(text(),'{sectionHeaderText}')]//following-sibling::img[contains(@class,'collapse-arrow')]");
Please try to avoid using text in the selector. The workflow should be following
1. Locate all services sections
2. Find one with the appropriate properties (in this case this is a text)
3. Locate element in element

2023-01-31 08:39 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Pages/OurServices/QaAsServicePage.cs
> +        var arrowWrapper = Page.Locator(
s

2023-01-31 08:39 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Pages/OurServices/QaAsServicePage.cs
> +        return Page.Locator($"//div[@class='img-card-title'and contains(text(),'{cardHeader}')]//ancestor::div[@class='img-card']");
s

2023-01-31 08:39 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/SpecFlowTests/OurServices/QaAsAService/GoogleAnalyticsOnQaAsAService.feature
> +	Given User is on 'https://tech-stack.io/services/qa-as-a-service' page
Is is possible to avoid direct URLs usage?
In case of environment change or URL change we will need to update all tests

2023-01-31 08:39 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/SpecFlowTests/OurServices/QaAsAService/GoogleAnalyticsOnQaAsAService.feature
> +	Then User sees 'QAasAServPage' event category and 'QAasAServCase' event action
Are you sure that this check should present here? Please use Then steps if this step is the thing that test case must verify
Same below

2023-01-31 08:39 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/GoogleAnalyticsEvents/QaAsServiceSteps.cs
> +        private IRequest MakeActionAndGetGoogleAnalyticsRequest(Action action)
Maybe it is make sense to rename to something like
RunActionAndGetGoogleAnalyticsRequest?

2023-01-31 08:39 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/GoogleAnalyticsEvents/QaAsServiceSteps.cs
> +        [When(@"User clicks 'Request A Quote' button in the header section")]
Use quotes only for parameters

2023-01-31 08:39 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/GoogleAnalyticsEvents/QaAsServiceSteps.cs
> +        [When(@"User clicks 'Request A Quote' button in the 'Our Approach' section")]
s

2023-01-31 16:49 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Pages/OurServices/QaAsServicePage.cs
> +    public string Container => "//div[@id='header']//parent::body";
that's the only way to get a container for the whole page because the page is split by sections, so in another case, it needs to create a pageObject for each section that only creates many one-line objects, IMHO it's better that another variant, @VitaliiDolotov  what you think about it?

2023-03-27 10:38 UTC, closed without merging