Internet of things tests - Content
tech-stack-dev/ts-website-automation pull request #193
Opened 2023-09-06 12:15 UTC by ysukhova

2023-09-06 16:19 UTC, Valerii-Kryvokhyzha requested changes

2023-09-06 16:19 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesContent.test.ts
> +	const ioTEngineeringCaseStudiesContainer = driver.getByTestId(IoTEngineeringServices.ioTEngineeringCaseStudies);
mb just
Check section titles and image....
OR
sen**s**or

2023-09-06 16:19 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesContent.test.ts
> +});
could you use
await expect(driver.getByTestId(IoTEngineeringServices.sensorsScheme)).toBeVisible();

2023-09-06 16:19 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesContent.test.ts
> +		'Cost savings from addressing over/undercooling',
pls check also numbers and IoT "humidity sensors scheme" block title

2023-09-06 16:19 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesContent.test.ts
> +	expect(await ioTEngineeringProcessContainer.getByTestId(Container.BlockTitle).textContent()).toEqual('New IoT Device\nEngineering');
pls check carousel numbers and SectionTitles in "New IoT Device Engineering" block

2023-09-07 07:18 UTC, Valerii-Kryvokhyzha requested changes

2023-09-07 08:56 UTC, Valerii-Kryvokhyzha approved these changes

2023-09-07 10:58 UTC, anastasiia-liashova approved these changes

2023-09-07 11:07 UTC, merged