Internet of things tests-actions
tech-stack-dev/ts-website-automation pull request #198
Opened 2023-09-08 12:03 UTC by ysukhova

![image](https://github.com/tech-stack-dev/ts-website-automation/assets/121864741/a8472b1a-366d-43f5-b41f-e4771d550f95)

2023-09-11 11:29 UTC, DaniilVostrikov requested changes

2023-09-11 11:29 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesActions.test.ts
> +			await driver.Page.locator(format(IoTEngineeringServices.LayerButton, layerButtonIndex++)).click();
lets avoid such a way of using locators pls

2023-09-11 11:29 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesActions.test.ts
> +	const expectedMemberCardsLinks: {blogLink: string; linkedInLink: string}[] = [
please use interpolation instead of contatination

2023-09-11 11:29 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesActions.test.ts
> +		/* TODO: Uncomment Blog related checks after TSWEB-1061 is done
let's skip the test with a jira tag

2023-09-11 11:29 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesActions.test.ts
> +function getRandomIntInRangeExcluding(min: number, max: number, excludedNumber: number): number {
Please do not store utils like this in test files

2023-09-11 11:29 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesActions.test.ts
> +		let randomLayerIndex = getRandomIntInRangeExcluding(0, containerBlocks.length - 1, i);
please replace this random checks with verifying of all unactive elements, it will be more complicated than random checks

2023-09-11 11:32 UTC, DaniilVostrikov requested changes

2023-09-11 11:32 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/identifiers/MainSite/pages/services/IoTEngineeringServices.ts
> +	static LayerButton = `//label[@data-id="Button-%s_Layer"]/div`;
Please contact @anastasiia-liashova to fix this data-id

2023-09-11 12:46 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesActions.test.ts
> +function getRandomIntInRangeExcluding(min: number, max: number, excludedNumber: number): number {
@DaniilVostrikov It's not actually a util function, but a custom function for the certain test. If you consider it as potentially useful for other tests, I'll add to the test utils.

2023-09-12 16:35 UTC, Valerii-Kryvokhyzha requested changes

2023-09-12 16:35 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesActions.test.ts
> +test('Check carousel buttons in "IoT Engineering Prodcess" container. @Regression @IoTEngineeringServices @TSWEB-695', async () => {
Process

2023-09-14 09:22 UTC, Valerii-Kryvokhyzha approved these changes

2023-09-14 10:57 UTC, KotliarovaK requested changes

2023-09-14 10:57 UTC, KotliarovaK commented on ui_tests_playwright/automation/test/ui/MainSite/services/ioTEngeneeringServices/IoTEngeneeringServicesActions.test.ts
> +test('Check Blog link redirects in "Our Internet of Things Engineering Experts" container. @Regression @IoTEngineeringServices @TSWEB-695, TSWEB-1061', async () => {
Could you please add "@" to "TSWEB-1061"

2023-09-14 11:51 UTC, KotliarovaK approved these changes

2023-09-14 14:13 UTC, DaniilVostrikov approved these changes

2023-09-14 14:27 UTC, merged