Updated tests for Cloud Development page
tech-stack-dev/ts-website-automation pull request #201
Opened 2023-09-12 15:39 UTC by Valerii-Kryvokhyzha

2023-09-12 15:41 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/CloudDevelopment/CloudDevelopmentContent.test.ts
> +
Need to add data-id (don't merge!)

2023-09-13 13:20 UTC, DaniilVostrikov approved these changes

2023-09-13 15:13 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/CloudDevelopment/CloudDevelopmentActions.test.ts
> +test.skip("Check redirects by Blog buttons in 'Our Leading Cloud Experts' container from the 'Cloud Development' page @Regression CloudDevelopment @TSWEB-692", async () => {
just add @TSWEB-1061 tag and remove skip and comment

2023-09-14 09:42 UTC, ysukhova requested changes

2023-09-14 09:42 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/CloudDevelopment/CloudDevelopmentActions.test.ts
> +test("Check redirects by Blog buttons in 'Our Leading Cloud Experts' container from the 'Cloud Development' page @Regression CloudDevelopment @TSWEB-692 @TSWEB-1061", async () => {
Blog is unstable, isn't it? Should the test be skipped?

2023-09-14 09:42 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/CloudDevelopment/CloudDevelopmentActions.test.ts
> +		[containerSection.nth(0).getByTestId(Container.Arrow), UrlProvider.urlBuilder(UrlPath.CustomDev)],
What if you get all Container.Arrow in the section at once, instead of getting them one by one each time? So it simplifies the code readability

2023-09-14 09:47 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/CloudDevelopment/CloudDevelopmentActions.test.ts
> +test("Check redirects by Blog buttons in 'Our Leading Cloud Experts' container from the 'Cloud Development' page @Regression CloudDevelopment @TSWEB-692 @TSWEB-1061", async () => {
yes, I skipped it with @TSWEB-1061 tag

2023-09-14 14:20 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/CloudDevelopment/CloudDevelopmentActions.test.ts
> +		[containerSection.nth(0).getByTestId(Container.Arrow), UrlProvider.urlBuilder(UrlPath.CustomDev)],
Fixed

2023-09-14 14:32 UTC, Valerii-Kryvokhyzha commented
remove breadcrumbs from IoT

2023-09-14 14:54 UTC, ysukhova approved these changes

2023-09-14 15:02 UTC, merged