TSWEB-1058 FAQ sections expanding
tech-stack-dev/ts-website-automation pull request #203
Opened 2023-09-12 15:58 UTC by Valerii-Kryvokhyzha

2023-09-12 16:00 UTC, Valerii-Kryvokhyzha commented
Add for IoT and match with Cloud Development @Valerii-Kryvokhyzha

2023-09-14 10:26 UTC, ysukhova requested changes

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/base/step/BaseDriverSteps.ts
> +			expect(isCollapsed).toBeTruthy();
It seems there is no need for this separate function wrapping assertions. The functions never returns false. In case any assertion triggers false, the test will fail. Also, getting isCollapsed value confronts the format of checks in 134-137 lines where you expect the opposite. Please review.

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/CustomDev/CustomDevActions.test.ts
> +	const epectedNumberOfSections = 5;
typo - expected

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/OurServices.test.ts
> +	const epectedNumberOfSections = 9;
typo

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/ConsaltingService/ConsultingServiceActions.test.ts
> +	const epectedNumberOfSections = 5;
typo

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/Cloud Development.test.ts
> +	const epectedNumberOfSections = 7;
typo

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/BigDataAndAnalytics.test.ts
> +	const epectedNumberOfSections = 4;
typo

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/AiMlService/AiMlServiceActions.test.ts
> +	const epectedNumberOfSections = 3;
typo

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/industries/RenewableEnergy/RenewableEnergyActions.test.ts
> +	const epectedNumberOfSections = 5;
typo

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/industries/Healthcare/HealthcareActions.test.ts
> +	const epectedNumberOfSections = 3;
typo

2023-09-14 10:26 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/MobileDevService.ts/MobileDevServiceActions.test.ts
> +	const epectedNumberOfSections = 4;
Please check all files where a similar variable is used to fix typo - 'expected...'

2023-09-19 17:57 UTC, ysukhova requested changes

2023-09-19 17:57 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/UxUiDesign/UxUiDesignContent.test.ts
> +	await expect(allSectionTitles).toHaveText(testData);
What about optimizing 130-159 lines in the following way:
```
for (let i = 1; i <= 11; i++) {
		const sectionNumber = i.toString().padStart(2, '0');
		await expect(carousel.getByTestId(Container.SectionNumber).nth(i - 1)).toHaveText(sectionNumber);
	}

	await expect(carousel.getByTestId(Container.SectionTitle)).toHaveText([
		'Business requirements allocation',
		'Market and business domain analysis',
                ...]);
```

2023-09-21 18:38 UTC, ysukhova approved these changes

2023-09-22 14:18 UTC, DaniilVostrikov approved these changes

2023-09-22 14:46 UTC, merged