TSWEB-1077 upd Big Data page
tech-stack-dev/ts-website-automation pull request #205
Opened 2023-09-13 15:22 UTC by Valerii-Kryvokhyzha

2023-09-14 10:39 UTC, ysukhova requested changes

2023-09-14 10:39 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/BigDataAndAnalytics/BigDataAndAnalyticsActions.test.ts
> +		[containerSection.nth(0).getByTestId(Container.Arrow), UrlProvider.urlBuilder(UrlPath.CustomDev)],
To simplify the code and improve its readability, please get all Container.Arrows outside the map.

2023-09-15 07:05 UTC, ysukhova approved these changes

2023-09-15 08:13 UTC, anastasiia-liashova approved these changes

2023-09-15 09:17 UTC, DaniilVostrikov requested changes

2023-09-15 09:17 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/MainSite/services/BigDataAndAnalytics/BigDataAndAnalyticsActions.test.ts
> +test("Check redirect by 'Read more about Solution' button in 'Big Data Case Studies' container from the 'Big Data & Analytics' page @Regression @BigDataAndAnalytics @TSWEB-693", async () => {
use ' ' instead of " " for test names

2023-09-15 11:05 UTC, DaniilVostrikov approved these changes

2023-09-15 11:32 UTC, merged