TSWEB-1080 upd Mobile page
tech-stack-dev/ts-website-automation pull request #207
Opened 2023-09-15 11:44 UTC by Valerii-Kryvokhyzha

2023-09-15 13:32 UTC, DaniilVostrikov approved these changes

2023-09-15 14:47 UTC, ysukhova requested changes

2023-09-15 14:47 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/MobileDevService.ts/MobileAppDevelopmentActions.test.ts
> +	const numberOfClicks = 3;
there is a single usage of numberOfClicks, so there is no real need to have it a separate variable

2023-09-15 14:47 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/MobileDevService.ts/MobileAppDevelopmentContent.test.ts
> +	await expect(allSectionTitles).toHaveText(testData);
Please separate checks from the rest of the code with an empty line

2023-09-15 14:47 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/MobileDevService.ts/MobileAppDevelopmentContent.test.ts
> +	const numberOfImages = 3;
there is a single usage of numberOfImages, so there is no real need to have it a separate variable

2023-09-15 14:47 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/MobileDevService.ts/MobileAppDevelopmentContent.test.ts
> +	await expect(allSectionTitles).toHaveText(testData);
Please separate checks from the rest of the code with an empty line

2023-09-15 14:47 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/MobileDevService.ts/MobileAppDevelopmentContent.test.ts
> +	await expect(allSectionTitles).toHaveText(testData);
Please separate checks from the rest of the code with an empty line

2023-09-15 14:54 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/MainSite/MainSiteImages.ts
> +
Good point, but it's id not for specific img, but for Big numbers on site, which represented as images.
I think it little bit different from img. But if you think that need to remove this brake - i 'll fix it

![image](https://github.com/tech-stack-dev/ts-website-automation/assets/118851019/045fc85a-31b1-45fb-99d1-2cf40b206196)

2023-09-15 14:58 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/MobileDevService.ts/MobileAppDevelopmentActions.test.ts
> +	const numberOfClicks = 3;
But in that way easier to understand for what this number need, without going inside a method. Should I remove this variable?

2023-09-15 14:59 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/MobileDevService.ts/MobileAppDevelopmentContent.test.ts
> +	const numberOfImages = 3;
The same to numberOfclicks. I think in this way more transparent. If need - i'll fix

2023-09-18 08:32 UTC, ysukhova approved these changes

2023-09-18 08:39 UTC, merged