IoT GA test
tech-stack-dev/ts-website-automation pull request #209
Opened 2023-09-15 18:24 UTC by ysukhova

![image](https://github.com/tech-stack-dev/ts-website-automation/assets/121864741/54f9c725-a045-45e1-998d-5513b46cbe29)

2023-09-20 11:21 UTC, anastasiia-liashova submitted a review, later dismissed

2023-09-20 12:14 UTC, ysukhova commented on ui_tests_playwright/automation/pages/GetInTouchPage.ts
> +export default class GetInTouchPage extends BasePage {
Waiting for data-id

2023-10-02 10:06 UTC, DaniilVostrikov approved these changes

2023-10-02 11:39 UTC, Valerii-Kryvokhyzha requested changes

2023-10-02 11:39 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/googleAnalytics/services/InternetOfThings.test.ts
> +	await driver.Page.reload();
pls change this row to
await driver.Page.getByTestId(Buttons.AcceptCookies).click();
because for now this problem is fixed and we have only one button with this identifier

2023-10-02 13:16 UTC, merged