Updated tests for UiUx page
tech-stack-dev/ts-website-automation pull request #213
Opened 2023-09-19 14:36 UTC by Valerii-Kryvokhyzha

2023-09-19 17:53 UTC, ysukhova requested changes

2023-09-19 17:53 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/UxUiDesign/UxUiDesignContent.test.ts
> +	await expect(carousel.getByTestId(Container.SectionNumber)).toHaveText([
What about shortening 130-159 lines in the following way:
```
for(let i = 1; i <= 11; i++) {
		const sectionNumber = i.toString().padStart(2, '0');
		await expect(carousel.getByTestId(Container.SectionNumber).nth(i-1)).toHaveText(sectionNumber);
	}

	await expect(carousel.getByTestId(Container.SectionTitle)).toHaveText([
		'Business requirements allocation',
		'Market and business domain analysis',
...]);
```

2023-09-19 17:53 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/services/UxUiDesign/UxUiDesignActions.test.ts
> +test.skip('Check redirect by Blog button in "We Never Stop Improving Your Product" container from the "UX/UI Design" page @Regression @UxUiDesign @TSWEB-670', async () => {
Please add jiraId for skip

2023-09-22 08:10 UTC, UncleDanya commented on ui_tests_playwright/automation/test/ui/MainSite/services/UxUiDesign/UxUiDesignActions.test.ts
> +	const clutchButton = successStoriesContainer.getByTestId(Buttons.Clutch);
Why do you declare a variable here if you only click on it next? You can click on it in one line.

2023-09-22 08:10 UTC, UncleDanya commented on ui_tests_playwright/automation/test/ui/MainSite/services/UxUiDesign/UxUiDesignActions.test.ts
> +	const behanceButton = weNeverStopImprovingContainer.getByTestId(Buttons.Behance);
same

2023-09-22 08:10 UTC, UncleDanya commented on ui_tests_playwright/automation/test/ui/MainSite/services/UxUiDesign/UxUiDesignContent.test.ts
> +	for (let i = 1; i <= 11; i++) {
Why you use hardcode here?

2023-09-22 08:25 UTC, ysukhova approved these changes

2023-09-22 10:18 UTC, anastasiia-liashova approved these changes

2023-09-22 10:49 UTC, UncleDanya approved these changes

2023-09-22 11:07 UTC, merged