About us page tests
tech-stack-dev/ts-website-automation pull request #214
Opened 2023-09-19 15:02 UTC by KotliarovaK

2023-09-19 16:26 UTC, Valerii-Kryvokhyzha requested changes

2023-09-19 16:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/MainSite/pages/company/AboutUs.ts
> +}
where this variable is used?

2023-09-19 16:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/company/AboutUs.test.ts
> +
pls add checks for 02 "What’s at the Core" block

2023-09-19 16:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/company/AboutUs.test.ts
> +
pls add checks for 04 "What makes us special" container

2023-09-19 16:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/company/AboutUs.test.ts
> +});
psl add checks for images

2023-09-19 16:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/company/AboutUs.test.ts
> +
pls add checks for 07 "Our people" container

2023-09-19 16:42 UTC, ysukhova requested changes

2023-09-19 16:42 UTC, ysukhova commented on ui_tests_playwright/automation/test/ui/MainSite/company/AboutUs.test.ts
> +		//[linkedInButtons[1], LinkedInReviewLinks.GrahamBrown], waiting for fix from https://ts-website.atlassian.net/browse/TSWEB-1040
Please use JiraId skip

2023-09-25 07:17 UTC, ysukhova approved these changes

2023-09-25 09:42 UTC, DaniilVostrikov approved these changes

2023-09-25 09:46 UTC, anastasiia-liashova approved these changes

2023-09-25 12:26 UTC, Valerii-Kryvokhyzha requested changes

2023-09-25 12:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/Buttons.ts
>  }
I think we have these identifiers in Container class

2023-09-25 12:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/MainSite/MainSiteButtons.ts
This identifier also exist in Container class

2023-09-25 12:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/MainSite/pages/company/AboutUs.ts
> +    static CarouselPhoto = 'CarouselPhoto';
mb better add this identifier to Container as it's not container?

2023-09-25 12:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/company/AboutUs.test.ts
> +	await expect(info.getByTestId(Container.Title)).toHaveText('We Make an Impact on\nthe Product, People, and\nWorld');
mb need to add breadcrumbs text check?

2023-09-25 12:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/company/AboutUs.test.ts
> +
should we need to add checking images in "Our partners" block?

2023-09-25 12:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/company/AboutUs.test.ts
> +
pls add "Join Us" button click

2023-09-25 12:28 UTC, Valerii-Kryvokhyzha requested changes

2023-09-28 08:07 UTC, Valerii-Kryvokhyzha approved these changes

2023-09-28 12:47 UTC, merged