Qa tsweb 1135
tech-stack-dev/ts-website-automation pull request #240
Opened 2023-10-31 14:03 UTC by KotliarovaK

2023-10-31 14:41 UTC, Valerii-Kryvokhyzha requested changes

2023-10-31 14:41 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/MainSite/pages/services/DigitalTransformation.ts
> +    static SuccessStories = 'Container-SuccessStories';
Seems like these (not only) data-ids already exist. Please run unit tests 
npm run unit-tests

2023-10-31 14:41 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/DigitalTransformation/DigitalTransformationContent.test.ts
> +test('Check the Info container from the "Digital Transformation Services" page @Regression @DigitalTransformation @TSWEB-1135', async () => {
*only comment
mb just "Digital Transformation" page ?

2023-10-31 14:41 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/DigitalTransformation/DigitalTransformationContent.test.ts
> +        driver.getByTestId(DigitalTransformation.TechnologyTransformationWorkflow),
smt with format (or only remote?)

2023-10-31 14:41 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/DigitalTransformation/DigitalTransformationContent.test.ts
> +test('Check section numbers and titles in "Digital Business Transformation Services" container from the "Digital Transformation Services" page @Regression @DigitalTransformation @TSWEB-1135', async (
mb add checking CTA text?

test('Check section numbers and titles, **and CTA** in "Digital Busi....

await expect(Container.getById(MainSiteButtons.CTA)).toHaveText(*text*);

2023-10-31 14:41 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/DigitalTransformation/DigitalTransformationContent.test.ts
> +	const industriesWeServeContainer = driver.getByTestId(DigitalTransformation.IndustriesWeServe);
test('Check section numbers and titles ....

2023-10-31 14:41 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/MainSite/services/DigitalTransformation/DigitalTransformationContent.test.ts
> +test('Check section titles, image and CTA button`s title in "Success Stories" container from the "Digital Transformation Services" page @Regression @DigitalTransformation @TSWEB-1135', async () => {
mb?
test('Check section titles, block title, image and CTA button in "Suc ...

and check for "IoT tracking and aggregation system scheme" block title (if needed)

2023-11-02 10:02 UTC, closed without merging

2023-11-02 10:02 UTC, KotliarovaK commented
no longer relevant