Added new actions tests in Digital Transformation
tech-stack-dev/ts-website-automation pull request #244
Opened 2023-11-08 11:57 UTC by KotliarovaK

2023-11-08 19:26 UTC, Valerii-Kryvokhyzha requested changes

2023-11-08 19:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/digitalTransformation/DigitalTransformationActions.test.ts
> +		driver.getByTestId(DigitalTransformation.Info).getByTestId(MainSiteButtons.RequestAQuote),
looks like it's not RequestAQuote button)

2023-11-08 19:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/digitalTransformation/DigitalTransformationActions.test.ts
> +		[arrows.nth(3), UrlProvider.urlBuilder(UrlPath.DevOpsServ)],
DevOps section without an arrow

2023-11-08 19:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/digitalTransformation/DigitalTransformationActions.test.ts
> +		[arrows.nth(5), UrlProvider.urlBuilder(UrlPath.UiUxDesign)],
numbers

2023-11-08 19:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/digitalTransformation/DigitalTransformationActions.test.ts
> +test('Check redirects by "Clutch Review" button in "Digital Transformation Strategy" container from the "Digital Transformation" page @Regression @DigitalTransformation @TSWEB-1135', async () => {
mb redirect?

2023-11-08 19:26 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/digitalTransformation/DigitalTransformationActions.test.ts
> +
mb clutchReviewButton

2023-11-09 08:16 UTC, Valerii-Kryvokhyzha approved these changes

2023-12-05 14:56 UTC, anastasiia-liashova approved these changes

2023-12-05 14:59 UTC, DaniilVostrikov approved these changes

2023-12-05 15:07 UTC, merged