back end page Content
tech-stack-dev/ts-website-automation pull request #274
Opened 2023-12-27 14:01 UTC by KotliarovaK

2023-12-27 14:53 UTC, Valerii-Kryvokhyzha requested changes

2023-12-27 14:53 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/backEndDevelopment/backEndDevelopmentContent.test.ts
> +test('Check section titles in "Techstack’s Powers\nin Back-End\nDevelopment" container from the "Back-End Development" page @Regression @BackEndDevelopment @TSWEB-1208', async () => {
pls remove \n from title)

2023-12-27 14:53 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/backEndDevelopment/backEndDevelopmentContent.test.ts
> +	const testData = ['.NET Stack', 'JVM Stack', 'Node.js Stack', 'Other'];
here you can use
const testData = TechnologyStackData.BackEndTab

2023-12-27 14:53 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/backEndDevelopment/backEndDevelopmentContent.test.ts
> +	const ourExpertsContainer = driver.getByTestId(BackEndDevelopment.OurExperts);
in  "Our Leading Back-End Engineers"

2023-12-27 14:53 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/backEndDevelopment/backEndDevelopmentContent.test.ts
> +test('Check section titles, numbers and CTA in "Back-End Development Services" container from the "Back-End Development" page @Regression @BackEndDevelopment @TSWEB-1208', async () => {
mb in "Back-End Development Services for Any Software Product"

2023-12-27 14:53 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/backEndDevelopment/backEndDevelopmentContent.test.ts
> +	const backendDevelopmentServicesContainer = driver.getByTestId(BackEndDevelopment.BackendDevelopmentServices);
mb same with container title

2023-12-27 14:53 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/backEndDevelopment/backEndDevelopmentContent.test.ts
> +		const title = await carouselSection.getByTestId(Container.SectionTitle).first().textContent();
can we romeve first() ?

2023-12-27 14:53 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/backEndDevelopment/backEndDevelopmentContent.test.ts
> +test('Check carousel section numbers and titles in "A Peek Into Back-End Process" container from the "Back-End Development" page @Regression @BackEndDevelopment @TSWEB-1208', async () => {
mb 
Check carousel section numbers and titles**, and CTA** in "A Peek Into Our Back-End Development Process" container...

2023-12-28 11:21 UTC, closed without merging

2023-12-28 11:23 UTC, KotliarovaK commented
Issues occurred while pushing