TSWeb-1274-Front-End-Development
tech-stack-dev/ts-website-automation pull request #281
Opened 2024-01-09 15:48 UTC by VeronikaDolbina

Added content and action tests for the Front-End Development page.

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha requested changes

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha commented on package-lock.json
> +        "husky": "^8.0.0"
why do we need to reduce version?

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/preconditionsData/links/ClutchReviewLinks.ts
> +	Anonymous = 'https://clutch.co/profile/techstack#review-2232982',
could you pls add more context?
eg AnonymousFounderNjorda or AnonymousNjorda or smt else

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentContent.test.ts
> +test('Check carousel section numbers and titles in "Front-End Development Process" container from the "Front End Development" page @Regression @FrontEndDevelopment @TSWEB - 1274', async () => {
@TSWEB-1274

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentContent.test.ts
> +test('Check section titles in "Related Services" container from the "Front End Development" page @Regression @FrontEndDevelopment @TSWEB - 1274', async () => {
@TSWEB-1274

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentContent.test.ts
> +test('Check section titles in "FAQ" container from the "Front End Development" page @Regression @FrontEndDevelopment @TSWEB - 1274', async () => {
@TSWEB-1274

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentContent.test.ts
> +test('Check section titles in "How We Can Help" container from the "Front End Development" page @Regression @FrontEndDevelopment @TSWEB-1274', async () => {
mb Check section numbers and titles...

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +
could you pls add checks for redirecting by links in "Frontend Web Development Services" container?

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +test('Check redirect by CTA button in "Case Studies" container from the "Front End Development" page @Regression @FrontEndDevelopment @TSWEB-1274', async () => {
could you pls provide full container name?
Check redirect by CTA button in "Front-End Development Services Case Studies" container ....

2024-01-09 18:35 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +
could you pls add check for redirect by "Clutch" link in "5.0-Star Clutch
Rating" section from "Why Techstack" container ?

2024-01-12 12:20 UTC, VeronikaDolbina commented on ui_tests_playwright/automation/preconditionsData/links/ClutchReviewLinks.ts
> +	Anonymous = 'https://clutch.co/profile/techstack#review-2232982',
Sure. I fixed.

2024-01-12 13:37 UTC, VeronikaDolbina commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +
I added a check.

2024-01-17 09:33 UTC, Valerii-Kryvokhyzha requested changes

2024-01-17 09:33 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +test('Check redirects by Blog buttons in "Our Front End Development Experts" container from the "Front End Development" page @Regression @FrontEndDevelopment @TSWEB-1274', async () => {
could you pls add @TSWEB-1061 tag to this test, to skip this test till the Blog will be Stable?

2024-02-01 15:14 UTC, Valerii-Kryvokhyzha requested changes

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha requested changes

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/backEndDevelopment/BackEndDevelopmentActions.test.ts
> +		const whyTechstackContainer = driver.getByTestId(GeneralContainersMainSite.WhyTechstack);
@VeronikaDolbina still actual

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +import GeneralContainersMainSite from '../../../../../identifiers/mainSite/GeneralContainersMainSite';
remove generalContainers pls and replace with appropriate page

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentContent.test.ts
> +import GeneralContainersMainSite from '../../../../../identifiers/mainSite/GeneralContainersMainSite';
s

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentContent.test.ts
> +test('Check carousel section numbers and titles in "Front-End Development Process" container from the "Front End Development" page @desktop @mobile @Regression @FrontEndDevelopment @TSWEB-1274', asyn
pls add CTA

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +	await baseDriverSteps.checkRedirectToPage(clutchReviewButton, ClutchReviewLinks.MarkBeare);
pls replace with checkRedirectToClutch()

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +	await baseDriverSteps.checkRedirectToPage(clutchLink, Links.ClutchReviews);
pls replace with checkRedirectToClutch()

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +	await baseDriverSteps.checkRedirectToPage(
s

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +test('Check carousel arrows clicks in "Front-End Development Process" container from the "Front End Development" page @desktop @mobile @Regression @FrontEndDevelopment @TSWEB-1274', async () => {
remove @mobile tag, as on mobiles there is no arrows, only static arousel

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/mainSite/MainSiteButtons.ts
> +	static TalkToAnExpert = 'Button-TalkToAnExpert';
remove pls

2024-06-21 10:21 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/identifiers/mainSite/MainSiteButtons.ts
> +	static ReceiveAFreeQuote = 'Button-ReceiveAFreeQuote';
remove pls

2024-06-21 10:25 UTC, Valerii-Kryvokhyzha requested changes

2024-06-21 10:25 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/services/frontEndDevelopment/FrontEndDevelopmentActions.test.ts
> +test('Check redirects by Blog buttons in "Our Front End Development Experts" container from the "Front End Development" page @desktop @mobile @Regression @FrontEndDevelopment @TSWEB-1061', async () =
pls also add @TSWEB-1274

2024-06-21 13:24 UTC, merged