First part of Forms refactoring to check regression after front-end changes
tech-stack-dev/ts-website-automation pull request #287
Opened 2024-01-19 15:45 UTC by Yevhenii-Ushynkin

2024-01-19 15:46 UTC, Yevhenii-Ushynkin commented
Ignore conflict for now

2024-02-02 19:12 UTC, Valerii-Kryvokhyzha requested changes

2024-02-02 19:12 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/steps/ui/FormSteps.ts
>  			await driver.getByTestId(Buttons.Send).click();
here locator found 2 elements with "Button-close" data-id, that's why this test fails

![image](https://github.com/tech-stack-dev/ts-website-automation/assets/118851019/74f77e10-e984-47c2-9c7e-2d1a7b7fbd4c)

2024-02-02 19:12 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/generalComponents/slack/SlackNotifications.test.ts
> +		'Check Slack notification from "staging_techstack_hr_notify" channel from Contact Us page @Regression @ContactUs @TSWEB-606 @TSWEB-1313'
I think we can remove @1313 ticket here to unskip test

2024-02-05 12:48 UTC, DaniilVostrikov approved these changes

2024-02-14 17:30 UTC, Valerii-Kryvokhyzha approved these changes

2024-02-16 20:33 UTC, merged