updated tests for Home Page
tech-stack-dev/ts-website-automation pull request #338
Opened 2024-07-29 10:30 UTC by VeronikaDolbina

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha requested changes

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
mb better to separate one file for Content and Actions?

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
> +	}
please add CTA text and include in title

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
> +			[clutchButtons[4], ClutchReviewLinks.AnonymousPeerToPeer],
incorrect authors order

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
pls add checking of "Request a quote" btn text in "case studies" container

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
> +		const bigNumberImages = workingWithBusinessesContainer.getByTestId(MainSiteImages.BigNumber).locator('visible=true');
why locator?

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
>  		await baseDriverSteps.checkRedirectToPage(clutchLink, Links.ClutchHighlights);
pls replace with checkRedirectToClutch()

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
> +		const clutchLink = workingWithBusinessesContainer.getByTestId(MainSiteLinks.Clutch).nth(0);
pls remove nth(0)

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
> +	}
pls also add CTA text (also upd test title)

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
> +test(
pls add test for "Recognition and Media Presence" container

2024-07-29 13:42 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
> +		}
why separated for 2 tests?

2024-07-29 13:46 UTC, VeronikaDolbina commented on ui_tests_playwright/automation/test/ui/mainSite/HomePage.test.ts
> +			[clutchButtons[4], ClutchReviewLinks.AnonymousPeerToPeer],
> incorrect authors order

this test has not been updated, it is skipped for now

2024-08-05 08:49 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePageContent.test.ts
> +
here we can add checking the text of Tecnology Stack tabs

2024-08-05 08:50 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePageActions.test.ts
> +		'Check the "Enhance Healthcare Strategy: Free Cloud Guide" container from the "Home" page @desktop @mobile @Regression @HomePage @TSWEB-1006'
better rename to something with redirect to...

2024-08-05 08:52 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePageActions.test.ts
> +);
can we unskip this test and update it?

2024-08-05 08:53 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePageActions.test.ts
> +
pls add here test for redirecting to case studies in "Case Studies" container

2024-08-05 08:55 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePageActions.test.ts
> +);
mb better to move to content test file?

2024-08-05 08:56 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePageActions.test.ts
> +
pls add here test for redirecting to links in "Recognition and Media Presence" container

2024-08-05 08:57 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/HomePageActions.test.ts
> +});
pls add test for FAQ expanding and colapsing

2024-08-05 16:23 UTC, Valerii-Kryvokhyzha approved these changes

2024-08-07 17:27 UTC, merged