Update tests for Case Study blocks
tech-stack-dev/ts-website-automation pull request #354
Opened 2024-10-14 15:53 UTC by SofiiaRostkovych

2024-10-14 16:09 UTC, VeronikaDolbina approved these changes

2024-10-15 12:52 UTC, VladFedash approved these changes

2024-10-15 13:16 UTC, DaniilVostrikov requested changes

2024-10-15 13:16 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/mainSite/services/digitalTransformation/DigitalTransformationContent.test.ts
> +		const actualIndexesAndTitles: Map<string, string> = new Map();
@SofiiaRostkovych upd code as we discussed in the places like here

2024-10-15 15:22 UTC, DaniilVostrikov approved these changes

2024-10-15 15:28 UTC, merged