Update tests for "Get a quote" button in the header
tech-stack-dev/ts-website-automation pull request #355
Opened 2024-10-16 14:39 UTC by SofiiaRostkovych

2024-10-16 16:53 UTC, Valerii-Kryvokhyzha requested changes

2024-10-16 16:53 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/generalComponents/header/headerMainSite/HeaderElementsColorChecks.test.ts
> +
We tack this btn text based on BW/Webflow ? Not by 50% random chance of displaying any version of btn to user?

2024-10-16 17:05 UTC, SofiiaRostkovych commented on ui_tests_playwright/automation/test/ui/generalComponents/header/headerMainSite/HeaderElementsColorChecks.test.ts
> +
on BW 'Book a strategy call' is the only version of btn displayed
on webflow pages btn was not updated, so it's 'Get a quote'

2024-10-16 17:10 UTC, Valerii-Kryvokhyzha approved these changes

2024-10-17 10:11 UTC, DaniilVostrikov requested changes

2024-10-17 10:11 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/generalComponents/header/headerMainSite/HeaderElementsColorChecks.test.ts
> +		if (webflowPages.includes(url)) {
please, try to use ternary expression here

2024-10-17 10:11 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/generalComponents/header/headerMainSite/HeaderFunctionalChecks.test.ts
> +				await baseDriverSteps.checkUrl(UrlProvider.urlBuilder(UrlPath.GetAQuote));
same here

2024-10-17 15:53 UTC, DaniilVostrikov approved these changes

2024-10-17 15:58 UTC, merged