TSWEB-1821 add tests calendly contact us/get a quote
tech-stack-dev/ts-website-automation pull request #362
Opened 2024-11-19 07:52 UTC by annalysokhmara

2024-11-19 10:37 UTC, DaniilVostrikov requested changes

2024-11-19 10:37 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/base/driver/BaseDriver.ts
> +	public frameLocator(selector: string, baseElement?: Locator): FrameLocator {
please try to use ternary operator instead of "if" conditions

2024-11-19 10:37 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/base/step/BaseDriverSteps.ts
> +
too much lb's, please remove some, between logic and expect for example

2024-11-19 10:37 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/mainSite/contactUs/ContactUsPage.test.ts
> +	for (let i = 0; i < allExperts.length; i++) {
please try not to rely on the indexes and sequence of the records, try to work with 2 arrays in other ways

2024-11-19 10:37 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/mainSite/contactUs/ContactUsPage.test.ts
> +	for (let i = 0; i < expertNames.length; i++) {
same

2024-11-19 10:37 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/mainSite/getAQuote/GetAQuotePage.test.ts
> +		const card = memberCards.nth(i);
same as above

2024-11-19 10:37 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/mainSite/getAQuote/GetAQuotePage.test.ts
> +	for (let i = 0; i < expertNames.length; i++) {
same as above

2024-11-20 15:41 UTC, DaniilVostrikov approved these changes

2024-11-20 18:24 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/mainSite/getAQuote/GetAQuotePage.test.ts
> +	const consultWithUsContainer = driver.getByTestId(GetAQuote.ConsultWithUs);
These tests are the same for 2 pages, as the blocks on the pages. Mb better to use 1 test with precondition of two links?

2024-11-24 12:57 UTC, annalysokhmara commented on ui_tests_playwright/automation/test/ui/mainSite/getAQuote/GetAQuotePage.test.ts
> +	const consultWithUsContainer = driver.getByTestId(GetAQuote.ConsultWithUs);
It has been implemented

2024-11-25 08:52 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/generalComponents/calendly/CalendlyBlockBusiness.test.ts
> +
on each page of testDataProvider checking of consult section will be twice? (for-of by "consultWithUsContainerList" inside testDataProvider)

2024-11-25 08:52 UTC, Valerii-Kryvokhyzha commented on ui_tests_playwright/automation/test/ui/generalComponents/calendly/CalendlyBlockBusiness.test.ts
> +	consultWithUsContainerList = [getAQuoteConsultWithUsContainer, contactUsConsultWithUsContainer];
mb better 1 identifier?

2024-11-25 09:48 UTC, DaniilVostrikov approved these changes

2024-11-25 14:28 UTC, annalysokhmara commented on ui_tests_playwright/automation/test/ui/generalComponents/calendly/CalendlyBlockBusiness.test.ts
> +	consultWithUsContainerList = [getAQuoteConsultWithUsContainer, contactUsConsultWithUsContainer];
agree, I'll imlement it with 1 identifier

2024-11-25 15:05 UTC, Valerii-Kryvokhyzha approved these changes

2024-11-25 16:32 UTC, merged