Fix tests steps
tech-stack-dev/ts-website-automation pull request #7
Opened 2023-01-11 12:45 UTC by anastasiia-liashova

2023-01-11 12:49 UTC, VitaliiDolotov commented on ui_tests/PlaywrightAutomation/Steps/ComponentSteps/PaginationComponentSteps.cs
> -                .BeTrue();
Why assert was removed? Should it be replaced by some other assertion?

2023-01-11 17:18 UTC, DaniilVostrikov requested changes

2023-01-11 17:18 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Steps/ComponentSteps/InputComponentSteps.cs
>              var inputElement =
please change inputElement => inputElementText

2023-01-11 17:18 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Steps/ComponentSteps/PaginationComponentSteps.cs
> +            paginationButton.IsVisibleAsync().GetAwaiter().GetResult().Should().BeTrue();
mb linebreaks?

2023-01-11 17:22 UTC, DaniilVostrikov requested changes

2023-01-11 17:22 UTC, DaniilVostrikov commented on ui_tests/PlaywrightAutomation/Steps/ComponentSteps/PaginationComponentSteps.cs
> +            var paginationButton = _page.Component<Pagination>().PaginationButtons.First;
mb better to use a pagination block to check visibility instead of some concrete(first) button?

2023-01-12 09:54 UTC, DaniilVostrikov approved these changes

2023-01-12 10:21 UTC, VitaliiDolotov approved these changes

2023-01-12 13:57 UTC, merged