Tsweb 532
tech-stack-dev/ts-website-automation pull request #95
Opened 2023-03-02 17:47 UTC by anastasiia-liashova

2023-03-07 19:30 UTC, YevheniiKel approved these changes

2023-03-07 19:52 UTC, VladFedash requested changes

2023-03-07 19:52 UTC, VladFedash commented on ui_tests_playwright/automation/identifiers/Button.ts
> +    // Services section
As we discussed previously, you can create some variable that will contain the "Sevices" part and it'll help you in the future if this section is changed 

But it's only my opinion and you can skip this comment if it is useless.

2023-03-07 19:52 UTC, VladFedash commented on ui_tests_playwright/automation/identifiers/Button.ts
> +    // Company section
same to this section

2023-03-07 19:52 UTC, VladFedash commented on ui_tests_playwright/automation/providers/UrlPath.ts
> +    static OurServices: string = "/services";
I would move the '/' char also to a staging string. 
It will seem more beautiful in this file and your staging string will work correctly anyway.
At least, we used it in such an approach in the dev project. (So it's up to you and our team)

2023-03-07 19:52 UTC, VladFedash commented on ui_tests_playwright/automation/providers/UrlProvider.ts
> +    public static urlBilder(urlPath: string) {
urlBuilder*

2023-03-07 19:52 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/ContactUs.test.ts
> +    let urlList: Array<string> = [
Wouldn't be better to send to UrlProvider.urlBilder() method our array with names of URLs we need ["UrlPath.OurServices", "UrlPath.CustomDev", ... , "UrlPath.ConsultingServ"] 
and inside a method urlBuilder() build paths and return an array? 

We will anyway create and initialize our array, but we'll call out the function only one time.

2023-03-07 19:52 UTC, VladFedash commented on ui_tests_playwright/automation/test/ui/ContactUs.test.ts
> +    for (let url of urlList) {
anyway, this block of code duplicates at least four times, I thought it'll be a separate method or anonymous function or smth like this. 
But if @DaniilVostrikov doesn't think so - I won't be against tp left it in such a view

2023-03-07 23:47 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/test/ui/ContactUs.test.ts
> +    let urlList: Array<string> = [
Well, we will still create an array, in any case. My implementation is more reusable. So the method returns one of the link and we can use this in other cases

2023-03-07 23:54 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/identifiers/Button.ts
> +    // Services section
Good point. If we have more buttons, we will divide them by logic

2023-03-09 11:55 UTC, DaniilVostrikov requested changes

2023-03-09 11:55 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/providers/UrlProvider.ts
> +    }
can these two methods be simplified in one, just adding some parameters and parameter checking?

2023-03-09 11:55 UTC, DaniilVostrikov commented on ui_tests_playwright/automation/test/ui/ContactUs.test.ts
> +    for (let url of urlList) {
Gonna discuss this with Nastya, and have an idea about the precondition

2023-03-09 16:09 UTC, DaniilVostrikov approved these changes

2023-03-09 16:20 UTC, VladFedash approved these changes

2023-03-10 10:29 UTC, merged