QA-TSWEB-560-CheckBreadcrumbsHeaderInJobsBlock
tech-stack-dev/ts-website-automation pull request #99
Opened 2023-03-14 15:18 UTC by DaniilVostrikov

moved CheckBreadcrumbsHeaderInJobsBlock test from .Net solution to ts framework, updated contentful logic

2023-03-14 15:44 UTC, VitaliiDolotov requested changes

2023-03-14 15:44 UTC, VitaliiDolotov commented on ui_tests_playwright/automation/base/driver/BaseDriver.ts
> +			try {
I would recommend to thorw exception in case of all attempts failed

2023-03-14 16:46 UTC, anastasiia-liashova commented on ui_tests_playwright/automation/base/driver/BaseDriver.ts
> +		let message = '';
Maybe `let message : string;`

2023-03-14 21:44 UTC, YevheniiKel approved these changes

2023-03-20 13:42 UTC, anastasiia-liashova approved these changes

2023-03-20 13:47 UTC, merged